version: '3.8'

services:
  backend:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./ai_notes:/ai_notes
      - ./videos:/videos  # Mount the videos directory
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=root
      - DEBUG=1
    depends_on:
      - db
    env_file:
      - .env 

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: root
      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
      LANGCHAIN_API_KEY: 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
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  videos: 